### ISSUE TITLE
flexible prediction function

### ISSUE THREAD

**Issue by finked** [finked/FaceRecognition#11]
Sollten wir für ünsere Prediction nicht sinvollerweise unterschiedliche Daten übergeben können? Ich wollte gerade eine Prediction für X_train machen, um die Fehler genauer zu untersuchen und muss das wieder komplett neu schreiben. Manchmal hat man ja vielleicht auch unterschiedliche Sets und möchte auf diese unabhängig voneinander eine Vorhersage machen.

**Comment by egolus** [comment]
hmm ja, wir könnten nen optionalen Parameter an [predict()](https://github.com/finked/FaceRecognition/blob/master/FacialKeypointRecognition.py#L155) übergeben

``` python
predict(self, X=None):
    if X is None:
        X = self.X_test
    self.prediction = self.network.predict(X)
```
