### ISSUE TITLE
parameter 'cols' in FacialKeypointRecognition.load

### ISSUE THREAD

**Issue by egolus** [finked/FaceRecognition#7]
zur Zeit kommt ein KeyError, wenn man auf einzelne Columns einschränken will

**Comment by finked** [comment]
Ich hab gerade auch nochmal versucht cols zu übergeben. In meinem jupyter notebook hatte eine liste an col namen funktioniert und als übergabewert gab es einen Fehler. Denke es wird zu einem string zusammengepackt und daher nicht mehr als unterschiedliche Listeneinträge erkannt!?

**Comment by egolus** [comment]
meine ersten manuellen Tests funktionieren. `cols` muss eine Liste von strings sein:

``` python
fkr.load(cols=['left_eye_center_x', 'left_eye_center_y'])
```

Edit: 
Ah, wenn über `loadData` aufgerufen, funktioniert es nicht .. da ist der Fehler

Edit2:
OK, ist einfach ein Denkfehler. 
`LoadData` fuehrt `load` 2x aus und gibt alle args weiter:

- ohne Änderungen der args fuer das Trainingsset
- mit zusaetzlichem `test=True` fuer das Testset

das Testset hat aber nur die `Image`-Spalte, da wir ja die Koordinaten selbst erkennen wollen. Daher darf der Parameter `cols` nur für das Trainingsset übergeben werden
